# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'xionghuahua' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
inhibit_all_warnings!
  # Pods for xionghuahua
  pod 'Moya'
  pod 'Kingfisher'
  pod 'MBProgressHUD'
  pod 'Then'
  pod 'UINavigation-SXFixSpace-Swift'
  pod 'HandyJSON'
  pod 'FCUUID'
  
  pod 'UMengAnalytics'
  
  pod 'Hue'
  
  pod 'R.swift'
  
end
